name = "AlgebraicArrays"
uuid = "8af735f6-f3e5-4048-bdaa-40a2355e9eea"
version = "1.0.11-DEV"
authors = ["G Jake Gebbie <ggebbie@whoi.edu>"]

[deps]
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[weakdeps]
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
AlgebraicArraysDimensionalDataExt = ["DimensionalData"]
AlgebraicArraysUnitfulExt = ["Unitful"]

[compat]
DimensionalData = "0.27,0.28,0.29"
Unitful = "1.21.0"
julia = "1.10,1.11,1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DimensionalData", "Unitful"]
